// Builds src/data/beforeafter.json: for each spot along the line, the Esri World Imagery Wayback
// release that shows the last imagery captured before construction began, and the latest release,
// each with its real capture date and provider from Esri's imagery metadata.
// Run: node scripts/build-wayback.mjs   (needs network; re-run to pick up newer imagery)
import { readFileSync, writeFileSync } from 'node:fs';

const CONFIG = 'https://s3-us-west-2.amazonaws.com/config.maptiles.arcgis.com/waybackconfig.json';
const BEFORE_LIMIT = 20240303; // foundation stone, 3 Mar 2024 (see timeline.json)
const ZOOM = 18;
const stations = JSON.parse(readFileSync(new URL('../src/data/stations.json', import.meta.url), 'utf8')).stations;

// Spots: stations where the viaduct runs along the road, plus the bend near Manpada.
const SPOTS = [
  { id: 'apmc-kalyan', station: 'apmc-kalyan', title: 'APMC Kalyan' },
  { id: 'dombivli-midc', station: 'dombivli-midc', title: 'Dombivli MIDC' },
  { id: 'golavli', station: 'golavli', title: 'Golavli' },
  { id: 'sonarpada', station: 'sonarpada', title: 'Sonarpada, Manpada Circle' },
];

const get = async (url) => {
  const r = await fetch(url, { headers: { 'User-Agent': 'line12-tracker build script' } });
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return r.json();
};

const releases = Object.entries(await get(CONFIG))
  .map(([id, v]) => ({ id, date: v.itemTitle.match(/\d{4}-\d{2}-\d{2}/)[0], tile: v.itemURL, meta: v.metadataLayerUrl }))
  .sort((a, b) => b.date.localeCompare(a.date));

async function captureAt(rel, lng, lat) {
  // Layer 4 is the 30 cm metadata layer, which covers these zoom levels.
  for (const layer of [4, 3, 5]) {
    const q = new URLSearchParams({
      geometry: `${lng},${lat}`, geometryType: 'esriGeometryPoint', inSR: '4326',
      spatialRel: 'esriSpatialRelIntersects', outFields: 'SRC_DATE,NICE_DESC,SRC_RES', returnGeometry: 'false', f: 'json',
    });
    const r = await get(`${rel.meta}/${layer}/query?${q}`);
    const a = r.features?.[0]?.attributes;
    if (a) return { date: String(a.SRC_DATE), provider: a.NICE_DESC, resolution_m: a.SRC_RES };
  }
  return null;
}
const iso = (d) => `${d.slice(0, 4)}-${d.slice(4, 6)}-${d.slice(6, 8)}`;

const out = {
  _meta: {
    description: 'Before and after satellite imagery for spots along Line 12, from Esri World Imagery Wayback. Generated by scripts/build-wayback.mjs; do not edit by hand.',
    zoom: ZOOM,
    before_rule: 'Latest imagery captured before 3 Mar 2024 (foundation stone).',
    last_reviewed: new Date().toISOString().slice(0, 10),
  },
  spots: [],
};

for (const spot of SPOTS) {
  const s = stations.find((x) => x.id === spot.station);
  const { lat, lng } = s.location;
  const after = releases[0];
  const afterCap = await captureAt(after, lng, lat);
  let before = null;
  let beforeCap = null;
  let lastDate = null;
  for (const rel of releases) {
    if (rel.date > '2024-06-30') continue;
    const cap = await captureAt(rel, lng, lat);
    if (!cap || cap.date === lastDate) continue; // same imagery as a newer release; keep walking back
    lastDate = cap.date;
    if (Number(cap.date) < BEFORE_LIMIT) {
      before = rel;
      beforeCap = cap;
      break;
    }
  }
  if (!before) throw new Error(`No pre-construction imagery found for ${spot.id}`);
  out.spots.push({
    id: spot.id,
    title: spot.title,
    station_id: spot.station,
    lat,
    lng,
    location_status: s.location.status,
    before: { release_id: before.id, release_date: before.date, tile_url: before.tile, captured: iso(beforeCap.date), provider: beforeCap.provider, resolution_m: beforeCap.resolution_m },
    after: { release_id: after.id, release_date: after.date, tile_url: after.tile, captured: iso(afterCap.date), provider: afterCap.provider, resolution_m: afterCap.resolution_m },
    status: 'verified',
    source_url: 'https://livingatlas.arcgis.com/wayback/',
    last_verified: out._meta.last_reviewed,
  });
  console.log(spot.id, iso(beforeCap.date), '->', iso(afterCap.date));
}

writeFileSync(new URL('../src/data/beforeafter.json', import.meta.url), JSON.stringify(out, null, 2) + '\n');
console.log('Wrote src/data/beforeafter.json');
