"""Generates src/components/LeadPicture.astro: an isometric, flat-shaded drawing of
the Line 12 viaduct and a generic 3-car train. Original geometry, not an official design.
Run: python scripts/draw-lead-picture.py
World units are metres: x runs along the line (up-right on screen), y across it
(down-right, toward the viewer), z up. Only the top, +y and -x faces are visible."""
import math

C, S = math.cos(math.radians(30)), 0.5
K = 6.0  # px per metre

def P(x, y, z):
    return ((x + y) * C * K, (-x * S + y * S - z) * K)

def poly(pts, fill, extra=''):
    d = ' '.join(f'{a:.1f},{b:.1f}' for a, b in (P(*p) for p in pts))
    return f'<polygon points="{d}" fill="{fill}"{extra} />'

def box(x0, x1, y0, y1, z0, z1, top, front, side):
    """front = +y face, side = -x face."""
    return [
        poly([(x0, y0, z0), (x0, y1, z0), (x0, y1, z1), (x0, y0, z1)], side),
        poly([(x0, y1, z0), (x1, y1, z0), (x1, y1, z1), (x0, y1, z1)], front),
        poly([(x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)], top),
    ]

CON = ('var(--iso-con-top)', 'var(--iso-con-front)', 'var(--iso-con-side)')
out = []

# Road on the ground under the viaduct, with lane marks and a giant "12".
out.append(poly([(-60, -6, 0), (150, -6, 0), (150, 15, 0), (-60, 15, 0)], 'var(--iso-road)'))
for x in range(-60, 150, 14):
    out.append(poly([(x, 4.2, 0), (x + 7, 4.2, 0), (x + 7, 4.8, 0), (x, 4.8, 0)], 'var(--iso-mark)'))

# Ground in front of the road, and the giant "12" painted on it (Tren Urbano reference).
out.insert(0, poly([(-60, 15, 0), (150, 15, 0), (150, 50, 0), (-60, 50, 0)], 'var(--iso-ground)'))
out.append('__TWELVE__')

# Piers far to near (larger x is farther), then caps.
for x0 in (120, 90, 60, 30, 0, -30):
    out += box(x0, x0 + 2.2, 3.4, 5.6, 0, 12.2, *CON)
    out += box(x0 - 1.2, x0 + 3.4, 0.2, 8.8, 12.2, 13.6, *CON)

# U-girder deck and its two lips.
out += box(-60, 150, 0.4, 8.6, 13.6, 15.6, *CON)
out += box(-60, 150, 0.4, 1.0, 15.6, 16.8, *CON)

# Train: three stainless cars with an orange band and navy window strip.
T = ('var(--iso-car-top)', 'var(--iso-car-front)', 'var(--iso-car-side)')
for x0 in (58, 34.5, 11):
    x1 = x0 + 22.5
    out += box(x0, x1, 2.0, 5.2, 16.0, 19.8, *T)
    out.append(poly([(x0, 5.2, 17.0), (x1, 5.2, 17.0), (x1, 5.2, 17.7), (x0, 5.2, 17.7)], 'var(--signal)'))
    out.append(poly([(x0 + 1, 5.2, 18.1), (x1 - 1, 5.2, 18.1), (x1 - 1, 5.2, 19.1), (x0 + 1, 5.2, 19.1)], 'var(--iso-window)'))
    for dx in (5.5, 16):
        out.append(poly([(x0 + dx, 5.2, 16.2), (x0 + dx + 1.6, 5.2, 16.2), (x0 + dx + 1.6, 5.2, 19.1), (x0 + dx, 5.2, 19.1)], 'var(--iso-door)'))

# Near lip last, so it sits in front of the train's lower edge.
out += box(-60, 150, 8.0, 8.6, 15.6, 16.8, *CON)

# Frame: the stretch of line from x=-8 to x=92, ground to above the train roof.
xs, ys = [], []
for x in (-8, 92):
    for y in (-6, 46):
        for z in (0, 21):
            a, b = P(x, y, z); xs.append(a); ys.append(b)
pad = 12
vx, vy, vw, vh = min(xs) - pad, min(ys) - pad, max(xs) - min(xs) + 2 * pad, max(ys) - min(ys) + 2 * pad
view = f'{vx:.0f} {vy:.0f} {vw:.0f} {vh:.0f}'
# Clip everything to the frame so the long deck and road end cleanly at the edges.
CLIP = f'<clipPath id="lead-clip"><rect x="{vx:.0f}" y="{vy:.0f}" width="{vw:.0f}" height="{vh:.0f}" /></clipPath>'

# The giant "12" lies flat on the ground plane (x axis up-right, y axis down-right).
mx = f'matrix({C:.4f} {-S:.4f} {C:.4f} {S:.4f} {P(-4, 45, 0)[0]:.1f} {P(-4, 45, 0)[1]:.1f})'
twelve = f'<text transform="{mx}" font-family="Anek Latin Variable, sans-serif" font-weight="800" font-stretch="75%" font-size="{K*38:.0f}" fill="var(--iso-twelve)" letter-spacing="-4">12</text>'

svg = f'''<svg viewBox="{view}" role="img" aria-labelledby="lead-title" preserveAspectRatio="xMidYMid meet">
  <title id="lead-title">Isometric drawing of the Line 12 viaduct: concrete piers carry a U-girder deck over a road marked 12, and a three-car train runs on top.</title>
  <defs>{CLIP}</defs>
  <g clip-path="url(#lead-clip)">
  {chr(10).join('  ' + (twelve if o == '__TWELVE__' else o) for o in out)}
  </g>
</svg>'''

astro = f'''---
/* Generated by scripts/draw-lead-picture.py. Edit the script, not this file. */
---
<figure class="lead halftone">
  {svg}
  <figcaption>Illustration, not to scale. Original drawing, not an official design.</figcaption>
</figure>

<style>
  .lead {{
    --iso-con-top: #d4cdc1;
    --iso-con-front: #aaa295;
    --iso-con-side: #857d71;
    --iso-car-top: #f1eee8;
    --iso-car-front: #d9d5cd;
    --iso-car-side: #b3aea5;
    --iso-window: #1b2638;
    --iso-door: #8f8a82;
    --iso-road: rgb(12 20 34 / 0.85);
    --iso-mark: #efe9de;
    --iso-twelve: #0c1422;
    --iso-ground: rgb(12 20 34 / 0.08);
    margin: 0;
    background-color: var(--signal);
    --halftone: rgb(12 20 34 / 0.16);
  }}
  .lead svg {{
    width: 100%;
    height: auto;
    max-height: min(17rem, 34vh);
    
  }}
  .lead figcaption {{
    padding: var(--s-2) var(--s-3);
    font-size: var(--step--1);
    color: var(--on-signal);
  }}
</style>
'''
open('src/components/LeadPicture.astro', 'w', encoding='utf-8').write(astro)
print(view)
